### ISSUE TITLE
Getting missing module extproc issue

### ISSUE THREAD

**Issue by Cgopikri** [GoogleCloudPlatform/service-extensions#115]
## Expected Behavior
module named 'extproc' ,should be availble when using to call calloutserver(from extproc.service.callout_server import CalloutServer)

## Actual Behavior

Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/gvenka50/python-image/python-service-extensions/callouts/python/extproc/example/temp.py", line 24, in <module>
    from extproc.service.callout_server import CalloutServer
ModuleNotFoundError: No module named 'extproc'
## Steps to Reproduce the Problem

1.
1.
1.

## Specifications

- Version:
- Platform:

**Comment by martijneken** [comment]
Can you add repro commands? We are able to build working servers from these samples and tests are passing.
